import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useSettingsModalStyles = makeStyles({
    body: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalM,
        width: "100%",
        ...shorthands.padding(tokens.spacingVerticalS, 0),
    },
    columns: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
        gap: tokens.spacingHorizontalL,
        alignItems: "start",
        width: "100%",
    },
    mainColumn: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalM,
        minWidth: 0,
    },
    sideColumn: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalM,
        minWidth: 0,
    },
    section: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXS,
    },
    mainPanel: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
        ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalM),
        ...shorthands.borderRadius(tokens.borderRadiusLarge),
        backgroundColor: tokens.colorNeutralBackground2,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    sidePanel: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
        ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalM),
        ...shorthands.borderRadius(tokens.borderRadiusLarge),
        backgroundColor: tokens.colorNeutralBackground2,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    toggleGroup: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
    },
    shortcutsList: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
        maxHeight: "180px",
        overflowY: "auto",
        ...shorthands.padding(tokens.spacingVerticalXS, tokens.spacingHorizontalS),
        ...shorthands.borderRadius(tokens.borderRadiusMedium),
        backgroundColor: tokens.colorNeutralBackground2,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    shortcutRow: {
        display: "grid",
        gridTemplateColumns: "160px 1fr",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
    },
    shortcutKeys: {
        color: tokens.colorBrandForeground1,
        fontFamily: tokens.fontFamilyMonospace,
        fontSize: tokens.fontSizeBase200,
    },
    description: {
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
        lineHeight: tokens.lineHeightBase200,
    },
    actions: {
        display: "flex",
        justifyContent: "flex-end",
        gap: tokens.spacingHorizontalS,
        ...shorthands.padding(tokens.spacingVerticalS, 0, 0),
    },
});
